### ISSUE TITLE
Update Reference Genome section to address the genome_build option

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/rnaseq#13]
Consider the following `O2.yaml`:

```
details:
  - analysis: RNA-seq
    genome_build: mm10
    algorithm:
      transcriptome_fasta: /n/scratch2/abc/reference/Mus_musculus.GRCm38.cdna.all.fa
      transcriptome_gtf: /n/scratch2/abc/reference/Mus_musculus.GRCm38.95.gtf
      aligner: hisat2
      strandedness: firststrand
      spikein_fasta:  /n/scratch2/abc/reference/ERCC92/ERCC92.fa
```

As pointed out by Rory, the `transcriptome_fasta` setting usurps `genome_build`. While the current version of the instructions discusses specifying cdna vs. cdna+ncrna through `transcriptome_fasta`, it doesn't address the redundancy with `genome_build`.
